# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /uio/hume/student-u39/lythbh/IN3160/Oblig10/O10-platform/O10-platform.srcs/sources_1/bd/O10_block_design/ip/O10_block_design_rst_ps7_0_50M_0/O10_block_design_rst_ps7_0_50M_0.xci
# IP: The module: 'O10_block_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /uio/hume/student-u39/lythbh/IN3160/Oblig10/O10-platform/O10-platform.gen/sources_1/bd/O10_block_design/ip/O10_block_design_rst_ps7_0_50M_0/O10_block_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'O10_block_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /uio/hume/student-u39/lythbh/IN3160/Oblig10/O10-platform/O10-platform.gen/sources_1/bd/O10_block_design/ip/O10_block_design_rst_ps7_0_50M_0/O10_block_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'O10_block_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /uio/hume/student-u39/lythbh/IN3160/Oblig10/O10-platform/O10-platform.gen/sources_1/bd/O10_block_design/ip/O10_block_design_rst_ps7_0_50M_0/O10_block_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'O10_block_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /uio/hume/student-u39/lythbh/IN3160/Oblig10/O10-platform/O10-platform.srcs/sources_1/bd/O10_block_design/ip/O10_block_design_rst_ps7_0_50M_0/O10_block_design_rst_ps7_0_50M_0.xci
# IP: The module: 'O10_block_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /uio/hume/student-u39/lythbh/IN3160/Oblig10/O10-platform/O10-platform.gen/sources_1/bd/O10_block_design/ip/O10_block_design_rst_ps7_0_50M_0/O10_block_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'O10_block_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /uio/hume/student-u39/lythbh/IN3160/Oblig10/O10-platform/O10-platform.gen/sources_1/bd/O10_block_design/ip/O10_block_design_rst_ps7_0_50M_0/O10_block_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'O10_block_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /uio/hume/student-u39/lythbh/IN3160/Oblig10/O10-platform/O10-platform.gen/sources_1/bd/O10_block_design/ip/O10_block_design_rst_ps7_0_50M_0/O10_block_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'O10_block_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
