# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/O10_constraints.xdc

# Block Designs: bd/O10_block_design/O10_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==O10_block_design || ORIG_REF_NAME==O10_block_design} -quiet] -quiet

# IP: bd/O10_block_design/ip/O10_block_design_processing_system7_0_0/O10_block_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==O10_block_design_processing_system7_0_0 || ORIG_REF_NAME==O10_block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/O10_block_design/ip/O10_block_design_axi_gpio_0_0/O10_block_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==O10_block_design_axi_gpio_0_0 || ORIG_REF_NAME==O10_block_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/O10_block_design/ip/O10_block_design_system_0_0/O10_block_design_system_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==O10_block_design_system_0_0 || ORIG_REF_NAME==O10_block_design_system_0_0} -quiet] -quiet

# IP: bd/O10_block_design/ip/O10_block_design_auto_pc_0/O10_block_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==O10_block_design_auto_pc_0 || ORIG_REF_NAME==O10_block_design_auto_pc_0} -quiet] -quiet

# IP: bd/O10_block_design/ip/O10_block_design_ps7_0_axi_periph_0/O10_block_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==O10_block_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==O10_block_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/O10_block_design/ip/O10_block_design_rst_ps7_0_50M_0/O10_block_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==O10_block_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==O10_block_design_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: /uio/hume/student-u39/lythbh/IN3160/Oblig10/O10-platform/O10-platform.gen/sources_1/bd/O10_block_design/O10_block_design_ooc.xdc
